[build-system] 
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ACEsymmetry"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
description = "Interactive application for the determination of the symmetry elements in a molecule."
dependencies = [
    "rdkit",
    "streamlit",
    "streamlit_ketcher",
    "pointgroup",
    "numpy",
    "pubchempy",
    "xyzrender",
]
authors = [
    {name = "Cyrielle Salardi--Brahy", email = "cyrielle.salardi-brahy@epfl.ch"},
    {name = "Elodie Scherz", email = "elodie.scherz@epfl.ch"},
    {name = "Alexis Vayron", email = "alexis.vayrondelamoureyre@epfl.ch}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dynamic = ["version"]

[project.urls]
source = "https://github.com/csalardi/ACEsymmetry"
tracker = "https://github.com/csalardi/ACEsymmetry/issues"

[project.optional-dependencies]
test = [
    "hypothesis",
    "pytest",
    "pytest-cov",
    "tox",
    "genbadge[coverage]",
    "typer",
]
doc = [
    "furo",
    "myst-parser",
    "sphinx>=5",
    "sphinx-copybutton",
]

[tool.hatch.version]
path = "src/acesymmetry/__init__.py"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.coverage.run]
omit = [
    '__init__.py'
]

[tool.coverage.report]
exclude_also = [
    "if __name__ == .__main__.:",
]

[project.scripts]
acesymmetry_app = "acesymmetry.GUI.launcher:launch"
