import Conversion_xyz_from_name as conv

print("Testing for hydrogen")
print(conv.overall_conversion("Dihydrogen",None, "H2.SDF", "H2.xyz"))
print("Testing for Helium")
print(conv.overall_conversion("Helium", None, None, None))
print("Testing for invalid name")
print(conv.overall_conversion("fresh_butter", None, None, None))
print("Testing for benzene")
print(conv.overall_conversion("Benzene", None, None, None))
print("testing for propanol")
print(conv.overall_conversion("Propan-2-ol", None, None, None))
print("testing for butanol")
print(conv.overall_conversion("Butan-1-ol", None, "But-1-ol.SDF", "But-1-ol.xyz"))
print("Testing for ferrocene")
print(conv.overall_conversion("Dicyclopentadienyliron", None, None, None))
print("Testing for cisplatin")
print(conv.overall_conversion("cis-diamminedichloroplatinum(II)", None, None, None))
